### ISSUE TITLE
Django post office with mandrill/djrill not working

### ISSUE THREAD

**Issue by oneschilling** [ui/django-post_office#101]
Is there an easy way to use django post office with mandrill? I use djrill which provides its own email backend to communicate with mandrill. Since django post office also comes with its own backend it doesn't seem to work out of the box..

**Comment by selwin** [comment]
Yes, you can change Post office's email backend:

POST_OFFICE = {
    'EMAIL_BACKEND': 'django_ses.SESBackend'
}
