### ISSUE TITLE
I18N for model EmailTemplate

### ISSUE THREAD

**Issue by jrief** [ui/django-post_office#102]
For a project, which requires multi-lingual support, I'd like to add the possibility to add templates for translated content.
This means that I would add a new model with an n:1 relationship to ``EmailTemplate``. This new model, say ``TranslatedEmailTemplate``, will have the fields ``language``, ``subject``, ``content``, ``html_content`` and a foreign key to ``EmailTemplate``. In Django's backend it will be implemented as ``StackedInline`` with ``language`` as a Select widget offering all supported languages for this project.

When rendering email and ``django.translation.get_language()`` is identical with ``TranslatedEmailTemplate.language``, that template content is used, otherwise fall back to the template content from ``EmailTemplate``. This keeps **django-post_office** simple and backward compatible.

Would this feature proposal be accepted for this project and merged? I then would implement it and create a PR.

**Comment by jrief** [comment]
@selwin There is a PR now, please see #103

**Comment by selwin** [comment]
i18n is already supported in the master branch.
