### ISSUE TITLE
Basic support for read status

### ISSUE THREAD

**Issue by lucacorti** [ui/django-post_office#104]
It would be great if the system allowed for custom implementations of email read notification.

Ideally this could be just an additional state on the email, so that via custom links embedded in the messages one could set the model state to `delivered`.

**Comment by selwin** [comment]
If we support read status, there's also a bunch of other statuses like bounced, spam reports or clicks. Any suggestion on how this can be implemented?

I'm also not sure about whether this is suitable for inclusion in this library.

**Comment by lucacorti** [comment]
Maybe just an IntegerField one can map to custom states?

**Comment by yprez** [comment]
Tracking the states is the hard part.

For example, to get "read" status, you must embed a tracking image in the email, which means custom views, etc.

Clicks would mean replacing the all in the emails with custom redirect urls that count visits.

No idea how to get bounced/spam, etc. I think the only way to get that is from the smtp server...

**Comment by lucacorti** [comment]
Sure, also it is tricky to fit everyone's use cases. I was just requesting a "state" model field so consumers can implement custom behavior and meaning on top of that field.
