### ISSUE TITLE
Providing pre-formatted context variables when using templates

### ISSUE THREAD

**Issue by Seether85** [ui/django-post_office#106]
Would/is it possibile to do it?

So that for instance if I have something like:
`my_formatted_variable = "<ul>
    <li>First</li>
</ul>"`
and
`context={
'my_formatted_variable': my_formatted_variable,
}`
the resulting email (using template of course) would be *completely* formatted?
Because within the mail text I'm only obtaining the original tags right now:
`[...] &lt;ul&gt;&lt;li&gt;First&lt;/li&gt;&lt;/ul&gt; [...]`

Even with `mark_safe` nothing changes.

**Comment by selwin** [comment]
Tey using the |safe filter in the template instead of using mark_safe in the Python code. I think what's happening is that the variable loses it's safe attribute when it gets serialized into JSON.
