### ISSUE TITLE
Missinng Django migrations in version 2.0.0

### ISSUE THREAD

**Issue by yaniv14** [ui/django-post_office#108]
Hi,

It seems that in the new version you only added the south migration and not django migrations.

**Comment by selwin** [comment]
The file is here: https://github.com/ui/django-post_office/blob/master/post_office/migrations/0002_add_i18n_and_backend_alias.py . Is the migration file not in the pypi package?

**Comment by yaniv14** [comment]
I am not sure why my migration looks different, it seems that I have all south migrations files in the migration folder as well.
I just deleted the unnecessary files and everything is fine
