### ISSUE TITLE
Email.template not set when using render_on_delivery=False

### ISSUE THREAD

**Issue by yprez** [ui/django-post_office#110]
When calling send() with `render_on_delivery=False`, the resulting Email object's `template` field is not being set.
Is this on purpose?

It could be useful for tracking how many emails with this template were sent, etc...

**Comment by selwin** [comment]
Template is only needed when email is rendered during delivery so yes, this is actually on purpose.

Statistic tracking like how many times a template is used, or which email is read is another discussion altogether I think. There's a similar thread for this [here](https://github.com/ui/django-post_office/issues/104)

I'm open to suggestions on how this is implemented.

**Comment by yprez** [comment]
I was trying to add some logic to not send specific emails, if the same template was sent in the last N days.
All that is required for this is to keep some kind the reference between the email and the template that it originated from...

"Read status" is much more complicated than this.

If you take a look at #111, the changes there are pretty straightforward for this, although it breaks the rendering because emails with a template are considered as created with render_on_delivery, but their context is missing. I think that it's also easily fixable (didn't have time to check yet)...

If it's out of scope for post_office I'll can implement the same in another way probably.
