### ISSUE TITLE
Migrations not detected on 2.0.0

### ISSUE THREAD

**Issue by SeiryuZ** [ui/django-post_office#112]
I believe it might be a packaging problem, since I found other migrations file on the migration folder when finish installing from pip

![selection_475](https://cloud.githubusercontent.com/assets/1240672/8900492/bb7796ce-346a-11e5-8660-f0c04b000e3a.png)

**Comment by SeiryuZ** [comment]
Update:

.tar.gz from pypi is packaged with the correct migration folder 
.whl from pypi is the problem

**Comment by selwin** [comment]
Version 2.0.1 uploaded to PyPI.
