### ISSUE TITLE
Unable to send > 11,330 emails

### ISSUE THREAD

**Issue by kevgathuku** [ui/django-post_office#119]
Hello,
I am trying to send out a newsletter regularly with a combination of Post office and Django-RQ and every time I try to send it, it does not go beyond sending 11,330 emails despite having a sending list of about 14428 subscribers in my database. This has happened several times now. I'm just wondering if this is a problem with this package or if not, what the problem might be.
The relevant settings for Django Post office are:
```python
INSTALLED_APPS += ("post_office",)

POST_OFFICE = {
    'BACKENDS': {
        'default': 'djrill.mail.backends.djrill.DjrillBackend',
    },
    'DEFAULT_PRIORITY': 'now',
    'BATCH_SIZE': 1250,
    'LOG_LEVEL': 1,  # Log only failed deliveries
}

SOUTH_MIGRATION_MODULES = {
    "post_office": "post_office.south_migrations",
}

INSTALLED_APPS += ("django_rq",)

RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 360,
    },
    'high': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 500,
    },
    'low': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
    }
}
```
Package versions:
```
Django==1.8.4
django-post-office==2.0.1
django-rq==0.8.0
rq==0.5.5
```
I would appreciate any help. Thanks in advance.

**Comment by selwin** [comment]
Can you post the snippet of code that tries to send all those emails? My guess is at the worker gets killed by the job timeout before it finishes sending all emails.

**Comment by kevgathuku** [comment]
Thanks for taking the time to reply. Here's the task responsible for sending the newsletter
```python
@job
def sendnewsletter_task(newsletter_dict):
    for sub in subscribers:
        mail.send(
            [sub],
            sender='Name <name@example.com>',
            subject=newsletter_dict['title'],
            html_message=newsletter_dict['content'],
        )
```
I then call it with `sendnewsletter_task.delay(newsletter_dict)`

**Comment by selwin** [comment]
Yup, it's likely that your job exceeded maximum worker timeout. I suggest refactoring your code to split the sending process to multiple jobs, each sending 5k emails or similar.

For example:

```python

def sendnewsletter_task(newsletter_dict, subscribers): # call this function with a batch of 5k subscribers
    ...
```

**Comment by andela-kndungu** [comment]
I have a question regarding this. Would increasing the timeout have any effect in the first implementation?
