### ISSUE TITLE
Your models have changes that are not yet reflected in a migration, and so won't be applied.

### ISSUE THREAD

**Issue by madEng84** [ui/django-post_office#122]
If i launch a makemigrations i see a new post_office migration:
0003_auto_20151105_2015.py

I think you forgot adding the migration in the latest commit

**Comment by manuganji** [comment]
Yes, I believe this should resolve my local server issue

**Comment by amir-qayyum-khan** [comment]
I am getting same bug on running reverse migration.

**Comment by selwin** [comment]
This should be fixed in master. I also shipped the latest changes to PyPI.

**Comment by madEng84** [comment]
Thank you @manuganji @selwin **@scott**
