### ISSUE TITLE
Latest version on PyPI is 2.0.4

### ISSUE THREAD

**Issue by jrief** [ui/django-post_office#131]
but looking at the repository, the latest ist 2.0.2.
Did you forget to push?

**Comment by selwin** [comment]
I messed up the version numbering while working across computers. I just pushed out 2.0.5. Sorry for the confusion.

**Comment by yprez** [comment]
@selwin I think there's still something wrong, since the github version is `2.0.2` but it's `2.0.5` on pypi...
