### ISSUE TITLE
Add possibility to view attachments of e-mails

### ISSUE THREAD

**Issue by pkaczynski** [ui/django-post_office#141]
It can be helpful to verify if everything is ok before sending. Simple link to attachment in admin would be sufficient.

**Comment by selwin** [comment]
Could you please make a PR for this?

**Comment by yprez** [comment]
Btw, it won't be as simple as it sounds because Attachment.emails is a ManyToMany relationship, and a simple AdminInline won't work here...

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-post_office/pull/144
