### ISSUE TITLE
Post Office models' change not yet reflected in a migration

### ISSUE THREAD

**Issue by madEng84** [ui/django-post_office#146]
If I run a python manage.py migrate i have this warning:

> Your models have changes that are not yet reflected in a migration, and so won't be applied. Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

So, every time i make a "python manage.py makemigrations", will appears to me this migration:

> post_office.0003_auto_20160226_1752.py

Here is the detail:

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0002_add_i18n_and_backend_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(default='', help_text='Render template in alternative language', max_length=12, blank=True, choices=[(b'it', b'Italiano'), (b'de', b'Deutsche'), (b'fr', b'Francais'), (b'en', b'English')]),
        ),
    ]
```

Please commit this migration to pip (version :  2.0.5) because this warning is very annoying and i can't do 'makemigrations' for every app not to delete this migration at every 'makemigrations' command

Thank You and Best regards

**Comment by yprez** [comment]
@madEng84 I think this is fixed in master, because when I added a migration on #138 it generated an "alter field" that I didn't touch (was there before) https://github.com/ui/django-post_office/pull/138/files#diff-b6921e449ae020ca444ffed95787eb99R20
