### ISSUE TITLE
Django 1.9: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.

### ISSUE THREAD

**Issue by utapyngo** [ui/django-post_office#150]
lib/python2.7/site-packages/django/utils/six.py:808:
      RemovedInDjango110Warning: SubfieldBase has been deprecated.
      Use Field.from_db_value instead.

SubfieldBase is used by `CommaSeparatedEmailField`, see
https://github.com/ui/django-post_office/blob/e79dc8f304c80b6982178fa323760d1fc29f436c/post_office/fields.py#L9

**Comment by selwin** [comment]
Do you mind making a PR for this?

**Comment by utapyngo** [comment]
I don't know how to fix this correctly.
