### ISSUE TITLE
Should be able to specify attachments' mime types

### ISSUE THREAD

**Issue by georgema1982** [ui/django-post_office#155]
I'm using Sparkpost's email backend (https://github.com/SparkPost/python-sparkpost) along with post office. The problem is that Sparkpost's api seems very strict and requires each attachment to have mime type specified. It seems to me that there's no way to specify attachments' mime types in post office's API. Right now, I'm not able to use post office and Sparkpost out of box at this moment.

**Comment by Brandl** [comment]
Actually, I'm encountering a bug, when I try to send Mails with attachment, because also Django Core Mail (which is utilized by post_office), expects a Mimetype and is only presented with a binary string:
#164

**Comment by clickonchris** [comment]
We were having the same problem as @georgema1982 with Postmark as my email provider.

I've opened a PR that allows you to pass an explicit mime type when sending an attachment like this:

```
mail.send(
    ['recipient1@example.com'],
    'from@example.com',
    template='welcome_email',
    context={'foo': 'bar'},
    priority='now',
    attachments={
        'attachment.txt': {'file': ContentFile('file content'), 'mimetype': text/plain'}
    }
)
```

**Comment by georgema1982** [comment]
@clickonchris cool.
