### ISSUE TITLE
Post Office models' change not yet reflected in a migration (again)

### ISSUE THREAD

**Issue by rogeriomgatto** [ui/django-post_office#162]
There are still model changes not reflected on migrations in version 2.0.7 from pypi.  This is what is created:

```
$ ./manage.py makemigrations post_office
WARNING:root:Not reading settings for environment development: file not found
/home/.../venv/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

WARNING:py.warnings:/home/.../venv/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Migrations for 'post_office':
  0004_auto_20160607_1446.py:
    - Alter field language on emailtemplate
    - Alter field name on emailtemplate
```

The generated migration is attached (zipped): [0004_auto_20160607_1446.py.zip](https://github.com/ui/django-post_office/files/303224/0004_auto_20160607_1446.py.zip)

**Comment by rogeriomgatto** [comment]
By the way, at least on postgres, the generated migration doesn't alter anything on the database - it's apparently model metadata only.

**Comment by georgema1982** [comment]
I can confirm this issue after I upgrade da project from Django 1.6 to 1.7. Makemigrations would create this 0004 migration script.
