### ISSUE TITLE
Django 1.10 Bug

### ISSUE THREAD

**Issue by farnoodma** [ui/django-post_office#168]
Hi,
This app is not supported by new django version 1.10
The django throw an exception because of new release changes

Thanks for your excellent app :)

**Comment by b509** [comment]
My (more specific) problem is that, in post_office\fields.pyvhe tries to load
'from django.db.models import TextField, SubfieldBase'
but SubfieldBase does not seem to be there, because he throws an ImportError.

**Comment by Braintelligence** [comment]
So... is this fixed yet?

**Comment by andryr** [comment]
I use Django 1.10.5 and I don't have this issue

**Comment by selwin** [comment]
This has been fixed in the latest version.
