### ISSUE TITLE
Use custom credentials for smtp auth

### ISSUE THREAD

**Issue by paolodina** [ui/django-post_office#172]
I'm using Post Office in a site with 3 kinds of email, for:
- billing alerts (billing@domain.com)
- invitation mail (invite@domain.com)
- backup results (backup@domain.com)

settings.py:

```
EMAIL_HOST = 'smtp.domain.com'
EMAIL_HOST_USER = 'some_user@domain.com'
EMAIL_HOST_PASSWORD = '*****'
```

In Django `send_mail()` I can pass values to `auth_user` and `auth_password` parameters to use different user/password, but I don't find similar parameters in Post Office `send()` and wonder how to accomplish the same goal.

Any help?

**Comment by AliRezaBeitari** [comment]
Any updates?
