### ISSUE TITLE
TypeError at /admin/post_office/email/add/

### ISSUE THREAD

**Issue by kakulukia** [ui/django-post_office#193]
/site-packages/post_office/admin.py in _format_value, line 38
'NoneType' object is not iterable
    
    return ','.join([item for item in value]) 

I clicked on the add mail button inside the admin. 
Django 1.11.2
Python 3.6.1
PostOffice 2.0.8

**Comment by selwin** [comment]
Could you please upgrade to the latest PyPI version (3.0.2) and see if this is still an issue?

**Comment by kakulukia** [comment]
shall i actually be able to create an email by hand? i think its totally okay to just remove the add button in the admin .. i could create a pull request for this easily

**Comment by selwin** [comment]
You should be able to. I don't see why we wouldn't want to allow users to create user via Django's admin interface.

**Comment by kakulukia** [comment]
Sorry, but the issue is still existing in 3.0.2:
`/Users/andy/.virtualenvs/VFK_PORTAL-9ZY_FLJr/lib/python3.6/site-packages/post_office/admin.py in _format_value
        super(CommaSeparatedEmailWidget, self).__init__(*args, **kwargs)
        self.attrs.update({'class': 'vTextField'})
    def _format_value(self, value):
        # If the value is a string wrap it in a list so it does not get sliced.
        if isinstance(value, six.string_types):
            value = [value, ]
        return ','.join([item for item in value]) `

**Comment by selwin** [comment]
The patch for this issue was merged in just today https://github.com/ui/django-post_office/pull/195 and was released on PyPI as 3.0.3

**Comment by kakulukia** [comment]
i just upgraded my installation and currently pypi only lists 3.0.2 as the latest version .. will try again later .. cheers

**Comment by selwin** [comment]
Hi there, I checked PyPI and indeed 3.0.3 is not there, I probably made
some mistake cutting that release. I'll try to make a release again
tomorrow.


Win~

**Comment by kakulukia** [comment]
just installed from source because im preparing another PR and can confirm that adding email works in 3.0.3
BUT what about adding a log entry by hand, does that actually make sense?
