### ISSUE TITLE
send_queued_mail and scheduled_time

### ISSUE THREAD

**Issue by cwurld** [ui/django-post_office#196]
Hi,

I am using django-post-office to queue emails that I want to send several hours later. To do this, I am setting the "scheduled_time" keyword. My plan was to run the django command send_queued_mail every 15 minutes using cron. 

The problem is the "send_queued_mail" goes into a loop until the scheduled time. I need the send_queued _mail command to exit if all the queued emails are scheduled to be sent at a later datetime.

Thanks

**Comment by selwin** [comment]
This is fixed in https://github.com/ui/django-post_office/commit/5dc4d4778dc2dcb79b676d640497e63130069311 please upgrade to the newest PyPI release.
