### ISSUE TITLE
EMAIL_BACKEND ='post_office.EmailBackend' necessary?

### ISSUE THREAD

**Issue by racitup** [ui/django-post_office#208]
Is it absolutely necessary to have `EMAIL_BACKEND ='post_office.EmailBackend'` ?

I think this in general is not desirable. In a production environment you want to be notified as soon as possible of exceptions or problems with the site itself, so having important emails with errors going to the database is undesirable. This would also be a problem if post_office itself developed a problem, or even the database, which prevented all emails from being sent.

So I would argue it is a much safer configuration to keep the default email backend and have selected apps send their email to post_office directly.

**Comment by pkaczynski** [comment]
Wouldn't it be wiser to use logging facility to trace errors in the system instead? I would suggest using sentry (which can also send e-mails when something goes wrong on the site).

If I understand you correctly you want to send error messages using `AdminEmailHandler`. This handler is configurable, i.e. you can define a specific backend for the handler. See [this example](https://docs.djangoproject.com/en/2.0/topics/logging/#id4) for more details.

**Comment by selwin** [comment]
@racitup it's not absolutely necessary, but it's up to you :)
