### ISSUE TITLE
All ForeignKey migrations are required to contain on_delete in Django 2.0

### ISSUE THREAD

**Issue by coeal** [ui/django-post_office#216]
When running `python manage.py migrate`, all migrations throw an error saying that the migration file must contain on_delete for every ForeignKey migration (just as this is required for all ForeignKey model fields in models.py).

Relevant error info:
`  File ".../lib/python3.6/site-packages/post_office/migrations/0002_add_i18n_and_backend_alias.py", line 28, in Migration
    field=models.ForeignKey(related_name='translated_templates', default=None, to='post_office.EmailTemplate', null=True),
TypeError: __init__() missing 1 required positional argument: 'on_delete'`

Having gone through this process for my own app, every ForiegnKey modification in every migration will require the addition of an on_delete value otherwise migrations will fail.

Per Django 2.0 release notes:
"The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update."

**Comment by selwin** [comment]
Fixed in #217
