### ISSUE TITLE
Where to set SMTP credentials ?

### ISSUE THREAD

**Issue by alexsonnay** [ui/django-post_office#243]
Where can we setup SMTP credentials ? 

And also, I didn't get in the README where I should write that code : 

```
from post_office import mail

mail.send(
    'recipient@example.com', # List of email addresses also accepted
    'from@example.com',
    subject='My email',
    message='Hi there!',
    html_message='Hi <strong>there</strong>!',
)
```

**Comment by jrief** [comment]
In your project's `settings.py` use:

```
EMAIL_HOST = 'your-smtp-server'
EMAIL_PORT = 25 or 587
EMAIL_HOST_USER = 'smtp-user'
EMAIL_HOST_PASSWORD = 'smtp-secret'
EMAIL_USE_TLS = True or False
```

**Comment by alombardo83** [comment]
Hi @jrief,
Could we set multi configuration for smtp ?
Like

POST_OFFICE = {
    'BACKENDS': {
        'default': 'django.core.mail.backends.console.EmailBackend',
        'register': 'django.core.mail.backends.console.EmailBackend',
        'newsletter': 'django.core.mail.backends.console.EmailBackend',
        'message': {
            'backend': 'django.core.mail.backends.smtp.EmailBackend',
            'host': 'my-smtp-server',
            'username': 'my-smtp-user',
            'from': 'my-from-name',
            'password': 'my-password',
            'port': 465,
            'use_tls': False,
            'use_ssl': True
        },
    }
}

Thanks a lot

**Comment by jrief** [comment]
Check the Django settings for sending mail: https://docs.djangoproject.com/en/3.1/ref/settings/#email-host

As far as I know, you can not change them per backend. Something unsure, but maybe possible is to override those backends and code other configuration variables into it.
