### ISSUE TITLE
email sending failed

### ISSUE THREAD

**Issue by samazaphikel** [ui/django-post_office#271]
Hi,
I tried to use this app. But for me its not working. At this moment I used only local on my computer.

I created a new template and added in `admin/post_office/email/` 1 test email

When I leave the field Subject, Message, HTML MEssage empty and use a saved template. Then run via command line `python manage.py send_queued_mail`
 Then I get this error in the log

Exception type: TypeError
Message: context must be a dict rather than str.

Then I tried to send without a template and used the fields ubject, Message, HTML Message
 Then I get this error in the log

Exception type: ConnectionRefusedError
Message: [Errno 111] Connection refused

what do I have to do to use the script?

**Comment by jrief** [comment]
how did you put the message into the mailing queue?

**Comment by samazaphikel** [comment]
Sorry this was my issue...
i had a typo in the login...

But I have another question, is it possible to start the queue via the admin panel? or is it only possible via command line?
