### ISSUE TITLE
Compatibility issue with Django 3.0 due to django.utils.six

### ISSUE THREAD

**Issue by Mogost** [ui/django-post_office#274]
Django 3.0 scheduled for December removed Python 2 compatibility APIs used by django-post_office (django.utils.six, django.utils.encoding.python_2_unicode_compatible).

See https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis

It would be wise to switch now to the direct use of six.

**Comment by selwin** [comment]
PR welcome :)

**Comment by Mogost** [comment]
@selwin PR is ready. Could it be cheched, merged and released? Django already is on 3.0 **release candidate** stage.

**Comment by selwin** [comment]
I left a comment here: https://github.com/ui/django-post_office/pull/283#issuecomment-559630157

**Comment by Mogost** [comment]
@selwin My PR do only half of work.
Current dependency **jsonfield** is not supported. We have PR #219 with migration to **django-jsonfield** which is better supported (expect soon support for django 3.0).
**But** there is better way. We use json field only to store headers (Emails/Attachments), we can make 2 extra models like this:
```python
class AttachmentHeader(models.Model):
    attachment = models.ForeignKey(
        "post_office.Attachment",
        verbose_name=_("Attachment"),
        on_delete=models.CASCADE,
        related_name="headers",
    )
    name = models.TextField()
    value = models.TextField()
```
this approach will require a slightly larger code changes but solve the issue with JsonField once and for all.
