### ISSUE TITLE
how can i track unsent emails?

### ISSUE THREAD

**Issue by alikomijani** [ui/django-post_office#279]
hi, first i want to say thank you because of  your good job!
i have a question how can i track unsent emails for wrong email address?
i mean the email send by post office but not delivered by receiver because email address is wrong?

**Comment by jrief** [comment]
You mean wrong in the sense that they don't exist, or wrong that it's an unintended recipient?

**Comment by alikomijani** [comment]
i mean the email address is fake or doesn't exist

**Comment by jrief** [comment]
You can look into the Django-Admin. Post-Office logs the send-status of emails.
If that's the answer you expected, please close this issue.

**Comment by alikomijani** [comment]
https://pasteboard.co/IzCgU4c.png
https://pasteboard.co/IzChUlh.png
as you can see in this pic all the email address is fake but status is sent!
i want to find fake email after sending email ad remove them from my db
is any way to figure that?

**Comment by selwin** [comment]
This depends on your email service provider. Some providers can notify you in the case of delivery failures via webhook.
