### ISSUE TITLE
Setting expiration time on emails

### ISSUE THREAD

**Issue by selwin** [ui/django-post_office#281]
You may not want to send certain types of emails after a certain date. Rough ideas on how it should be implemented:
* Add `expiration_time` field on `Email`
* When email is picked up for processing in [send_queued()](https://github.com/ui/django-post_office/blob/master/post_office/mail.py#L181), if `expiration_time` is in the past, change the status to `expired`

**Comment by Houtmann** [comment]
Good idea, I can do this pull request
