### ISSUE TITLE
add support to Django 3.0

### ISSUE THREAD

**Issue by domdinicola** [ui/django-post_office#286]

**Comment by Mogost** [comment]
@domdinicola Please check for existing issues.
There is #274 about django 3.0 support, that is already done.
Currently i am workin on #284. Just **django-post_office** code support django 3.0, but we have dependency that does not support django 3.0.
We are not in a hurry to change the dependency, as it is likely that **JsonField** will change its owner soon and support for 3.0 will be added. https://github.com/rpkilby/jsonfield2/issues/8
_This issue should be closed._

**Comment by domdinicola** [comment]
I noticed that, I think we can close this when the package is compatible with django 3.0.
Hope you manage to get the ownership of the repo and update the jsonfield to make it compatible.

**Comment by Mogost** [comment]
But this issue is duplicate. Please close.

**Comment by domdinicola** [comment]
@Mogost last version still has some `python_2_unicode_compatible`, so we will need a new package (from master).
Regarding JSONField I got https://github.com/dmkoch/django-jsonfield/pull/234/files merged.
Please help me ask for a new release https://github.com/dmkoch/django-jsonfield/pull/235
So we can "finally" move to Django3.

**Comment by Mogost** [comment]
@domdinicola Please stop doing extra work.
We already have everything done in #285.
jsonfield2 is fully supported fork.
Also we are trying to name transfer from jsonfield to jsonfield2 in https://github.com/rpkilby/jsonfield2/issues/8

**Comment by Mogost** [comment]
@selwin please close that

**Comment by mmaridev** [comment]
Hi, what's going on here? The issue is still open so i assume we're not Django 3-ready or? :-(

**Comment by selwin** [comment]
The PyPI version is already djangon3 compatible
