### ISSUE TITLE
Choose the number of batches to send with command line

### ISSUE THREAD

**Issue by leogout** [ui/django-post_office#295]
Hello, I would like to limit the number of batch sent when I launch the `send_queued_mail` command. I know we can change the batch size, but not the number of batches to send before we stop. We can only send all of them if I am not mistaken.

My use case is that the SMTP I am using is my company's and it's preventing spam by allowing only 5 mails per minute per IP adress.

This is the solution I came up with, which is a bit tedious and is querying the database once more everytime a mail gets sent:
```python
from post_office import mail
from datetime import datetime, timedelta

send_at = datetime.now() + timedelta(minutes=Email.objects.filter(status=mail.STATUS.queued).count())
mail.send(
    subject=f'Hello',
    sender='hello@hey.fr',
    message='Hey how are you ?',
    recipients=('test@test.fr',),
    scheduled_time=send_at,
)
```
So that my mails get sent one by one every minute.

**Comment by jrief** [comment]
How about setting the `BATCH_SIZE` to say 5 and scheduling the delivery using a Celery beat with one minute intervals. This will deliver at maximum 5 emails to your SMTP-relay per minute.

**Comment by selwin** [comment]
What @jrief suggested. You can also do the same with `send_queued_mail` management command.
