### ISSUE TITLE
Is it possible to access the response from a ESP like Mailgun when sending via post_office?

### ISSUE THREAD

**Issue by rob101** [ui/django-post_office#298]
I am using `post_office` with `Mailgun`, supported via the [anymail ](https://anymail.readthedocs.io/) backend.

Is there a way to access the response from `Mailgun `when sending with `post_office`? Specifically I want to get the `message_id` so I can link the email to webhooks provided for `Mailgun` events (`open`, `click`, etc).

E.g. in `anymail `I would use the `AnymailMessageMixin` with:

```
message.send()
status = message.anymail_status  # available after sending
status.message_id  # e.g., '<12345.67890@example.com>'

```
However it's not clear how I would integrate that with `post_office`?

**Comment by selwin** [comment]
You can configure `post_office` to use any email backend you want, including `anymail`.

This is how you would configure custom backends:
```python
POST_OFFICE = {
    'BACKENDS': {
        'default': 'smtp.EmailBackend',
        'ses': 'django_ses.SESBackend',
    }
}
```
