### ISSUE TITLE
'Context' object has no attribute 'request' 

### ISSUE THREAD

**Issue by jucajuca** [ui/django-post_office#300]
Hello,

I want to render a template but I get the following error:
'Context' object has no attribute 'request' 

here is the code I am using:

views.py
```
        mail.send(
            [username],
            config.EMAIL_NOREPLY,
            context = {'request': request},
            template='pop_signup_successful',
            priority='now',
        )
```

this is a part of the report. This context seems malformed to me. The request is included but in an extra entry. And there is the bit with "{'True': True, 'False': False, 'None': None}" ???

```
Variable | Value
-- | --
context | [{'True': True, 'False': False, 'None': None}, {'request': <WSGIRequest: POST '/en/streets/register/'>}]
self | <fullurl.templatetags.fullurl.FullURLNode object at 0x7f73f7f38fd0>
url | '/en/accounts/password/reset/'
```

any ideas?

**Comment by jrief** [comment]
Mails are send outside of your normal HTTP request-response-cycle. Therefore there, you don't have a `request` object.
The solution is to write Django templates, which don't require the `request` object.

**Comment by jucajuca** [comment]
I see, but how would you build a valid url including the domain of the site?
this is a very standard case. For example: to confirm your email please click here...

**Comment by jrief** [comment]
You can set the context when calling `mail.send`. There you can build the absolute URL onto the email confirmation view.

**Comment by Flimm** [comment]
If you don't have the `request` object in the template, I would use the `sites` framework instead, like this:

    from django.contrib.sites.models import Site
    current_site = Site.objects.get_current()
    context = {'domain': current_site.domain}
    # etc
