### ISSUE TITLE
Is it possible to select different mail servers when sending email? Thank you

### ISSUE THREAD

**Issue by ptav** [ui/django-post_office#301]
It would be very helpful if different emails could be sent using different mailboxes. For example, emails to admins and emails to clients may require different From or ReplyTo data

There is already the ability to use various backends. Could this feature be enhanced by including the credentials and server information?

**Comment by jrief** [comment]
During the invocation of `mail.send()` you can override `From:` using the `sender` argument, it defaults to `settings DEFAULT_FROM_EMAIL `. If you just want to override the `Reply-To` address, do it through the `headers`.
