### ISSUE TITLE
duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by edenilsonfe** [ui/django-post_office#306]
**POST-OFFICE VERSION: 3.3.0**

hello,

I'm getting an error when I try to update an email template with a language that already exists. 

Steps:
1º - **Create** and **save** an email template in two languages (i.e. En / Es).
2º - Try to update the language of one of them to the same as the other.
result -> **IntegrityError**

![Screenshot 2020-04-22 at 13 57 12](https://user-images.githubusercontent.com/10874292/80010709-33177d80-84a1-11ea-86c5-8ac4c777708c.png)

Suggestion:
Create a validator to verify if the user is trying to save an email template using a language on the template that already exists.

Let me know if you already have a way to validate this. (if not, I can help with that)
Thanks

**Comment by jrief** [comment]
Bug Confirmed.

**Comment by jrief** [comment]
Please check if this branch works for your use-case:
https://github.com/ui/django-post_office/tree/fix-306-duplicate-key

**Comment by edenilsonfe** [comment]
These changes are pointing to 3.3.0 version? I ask this because I'm using Django 1.11 :)

**Comment by jrief** [comment]
I presume that you can merge that patch them into the 3.3.0 code base. It's just an additional validator on the form.

**Comment by edenilsonfe** [comment]
Thanks for your answer

**Comment by jrief** [comment]
Fixed by #310
