### ISSUE TITLE
Feature request: add user-friendly label field to EmailTemplate

### ISSUE THREAD

**Issue by madEng84** [ui/django-post_office#313]
It would be very useful to have in the model EmailTemplate a user-friendly `label` because the `name` field is used for matching purposes when associating a mail_template with an email

Would a pull request adding this simple functionality be accepted?

@jrief 

Thanks a lot for this fantastic package

**Comment by jrief** [comment]
Could you please show me where this happens. I'm using the `name` for human readable labels.
