### ISSUE TITLE
ModuleNotFoundError: No module named 'post_officeusers'

### ISSUE THREAD

**Issue by Dandada1993** [ui/django-post_office#316]
When doing migration "python manage.py migrate" the following error was encountered. Used pip to install latest version 3.4.1. Running VSCode on a Windows 7 Professional.

**Comment by jrief** [comment]
The app `django-post_office` does not import any module named `post_officeusers`, so this import statement must come from another source. Please recheck and if you found more evidence, reopen this issue.
