### ISSUE TITLE
Troubles using get_connection to make the connection dynamic

### ISSUE THREAD

**Issue by JViktoRArtola** [ui/django-post_office#341]
I' making the connection dynamic for example:

settings.py

```sh
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_BACKEND = 'post_office.EmailBackend'
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = '123s@123.sg'
# EMAIL_HOST_PASSWORD = '*********'
```

views.py *"passing get_connection to EmailMultiAlternatives"*
```sh
from django.core.mail import EmailMultiAlternatives, get_connection

def email_template_participants(arg):
    
    connection = get_connection(host=arg.email_backend.email_host, use_tls=arg.email_backend.use_tls,
                                port=arg.email_backend.port, username=email_back, password=arg.host_password)
    .......
    email_message = EmailMultiAlternatives(subject, body, from_email, to_email, connection=connection)
    template = get_template('email_participants.html', using='post_office')
    html = template.render(context_html)
    email_message.attach_alternative(html, 'text/html')
    email_message.attach_file(attach_file(id)
    template.attach_related(email_message)
    email_message.send()
```

* running this code : emails fail. On status: ConnectionRefusedError  ( Unable to establish a connection as the target computer expressly denied that connection )

* If I uncomment EMAIL_HOST, EMAIL_USE_TLS, etc the connection is denied, because they not always match, only works when they match, 1 in 15. 

**Otherwise. if I only change EMAIL_BACKEND to 'django.core.mail.backends.smtp.EmailBackend'. It works Perfect.**

### What can I do ????
**I need all Benefits from post_office, (crons, mails listed,  Requeue, retry_failed, etc )**

**Comment by selwin** [comment]
You need to specify which backends post office should use. Here's the docs: https://github.com/ui/django-post_office#custom-email-backends

**Comment by JViktoRArtola** [comment]
@selwin 
I think what I wanted to do was not well understood. That section is focused If I want to use a different backend and it works for that purpose. 

BUT.  What I want to do is use the function get_connection() that provide django.core.mail to make a dynamic connection.
All this info: EMAIL_HOST, EMAIL_USE_TLS 
, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD comes from Database

**Comment by selwin** [comment]
In that case, you'll need to create your own email backend that can dynamically alter it's connection based on your DB and set post office to use that like this:
```python
POST_OFFICE = {
    ...
    'BACKENDS': {
        'default': 'smtp.EmailBackend',
        'dynamic': 'MyDynamicBackend',
    }
}
```

**Comment by JViktoRArtola** [comment]
@selwin Thanks, The info about a custom backend in django docs is very little. https://docs.djangoproject.com/en/3.1/topics/email/#topic-custom-email-backend
Is there another example about how to do that?

**Comment by selwin** [comment]
No, unfortunately I don’t have anything concrete to refer you to.
