### ISSUE TITLE
Why validation is done on email.send instead of email.create? [question]

### ISSUE THREAD

**Issue by gabn88** [ui/django-post_office#408]
I'm writing a view to preview an email. Therefore it has to be saved to the database before sending. For that I use the mail.create function. It is however possible that when I want to send this email, the email is not valid. Because the validation occurs only on email.send. Is there a specific reason why the validation is postponed to send instead of on Email.create?

See create: https://github.com/ui/django-post_office/blob/3eb28369e94ca42a9002d47b70df06bdd5267711/post_office/mail.py#L29-L48

Vs send: https://github.com/ui/django-post_office/blob/3eb28369e94ca42a9002d47b70df06bdd5267711/post_office/mail.py#L98-L154

**Comment by selwin** [comment]
Because the API is designed like this :).
```python
from post_office import mail

mail.send(
    'recipient@example.com', # List of email addresses also accepted
    'from@example.com',
    subject='My email',
    message='Hi there!',
    html_message='Hi <strong>there</strong>!',
)
```

`Email.create` is actually just a shortcut to create the `Email` instance :)
