### ISSUE TITLE
HTML emails not stored correctly in database

### ISSUE THREAD

**Issue by gabn88** [ui/django-post_office#419]
Django is (sometimes) encoding the html part of EmailMessage as quoted_printable. In the following line we get this html message:
https://github.com/ui/django-post_office/blob/13aaac0d1575fb4805d71bc7f2ee390741eaec41/post_office/backends.py#L45

It might look like (message.as_string):
`'Content-Type: multipart/alternative;\n boundary="===============5112651050379218236=="\nMIME-Version: 1.0\nSubject: 123\nFrom: info@pareg.nl\nTo: info@pareg.nl\nDate: Thu, 06 Oct 2022 20:34:52 -0000\nMessage-ID: <166508849280.70920.10117324185103950413@1.0.0.127.in-addr.arpa>\n\n--===============5112651050379218236==\nContent-Type: text/plain; charset="utf-8"\nMIME-Version: 1.0\nContent-Transfer-Encoding: 7bit\n\n123\n--===============5112651050379218236==\nContent-Type: text/html; charset="utf-8"\nMIME-Version: 1.0\nContent-Transfer-Encoding: quoted-printable\n\n<!doctype html><html xmlns=3D"http://www.w3.org/1999/xhtml" xmlns:v=3D"urn:=\nschemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-microsoft-com:office:offi=\nce"><head><title>{% load i18n %}{% load static %} Welkom bij PaReg</title><=\n!--[if !mso]><!-- --><meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3De=\ndge"><!--<![endif]--><meta http-equiv=3D"Content-Type" content=3D"text/html=\n; charset=3DUTF-8"><meta name=3D"viewport" content=3D"width=3Ddevice-width,=\ninitial-scale=3D1"><style type=3D"text/css">#outlook a { padding:0; }\n          .ReadMsgBody { width:100%; }\n          .ExternalClass { width:100%; }\n          .ExternalClass * { line-height:100%; }\n          body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-=\nsize-adjust:100%; }\n          table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-tab=\nle-rspace:0pt; }\n          img { border:0;height:auto;line-height:100%; outline:none;text-de=\ncoration:none;-ms-interpolation-mode:bicubic; }\n          p { display:block;margin:13px 0; }</style><!--[if !mso]><!--><sty=\nle type=3D"text/css">@media only screen and (max-width:480px) {\n            @-ms-viewport { width:320px; }\n            @viewport { width:320px; }\n          }</style><!--<![endif]--><!--[if mso]>\n        <xml>\n        <o:OfficeDocumentSettings>\n          <o:AllowPNG/>\n          <o:PixelsPerInch>96</o:PixelsPerInch>\n        </o:OfficeDocumentSettings>\n        </xml>\n        <![endif]--><!--[if lte mso 11]>\n        <style type=3D"text/css">\n          .outlook-group-fix { width:100% !important; }\n        </style>\n        <![endif]--><style type=3D"text/css">@media only screen and (min-wi=\ndth:480px) {\n        .mj-column-per-100 { width:100% !important; max-width: 100%; }\n      }</style><style type=3D"text/css">@media only screen and (max-width:4=\n80px) {\n      table.full-width-mobile { width: 100% !important; }\n      td.full-width-mobile { width: auto !important; }\n    }</style></head><body style=3D"background-color:#E7E7E7;"><div style=3D=\n"display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;ma=\nx-width:0px;opacity:0;overflow:hidden;">Welkom bij PaReg! Verifieer eerst u=\nw mailadres.</div><div style=3D"background-color:#E7E7E7;"><table align=3D"=\ncenter" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presentati=\non" style=3D"background:#E7E7E7;background-color:#E7E7E7;width:100%;"><tbod=\ny><tr><td><!--[if mso | IE]><table align=3D"center" border=3D"0" cellpaddin=\ng=3D"0" cellspacing=3D"0" class=3D"" style=3D"width:600px;" width=3D"600" >=\n<tr><td style=3D"line-height:0px;font-size:0px;mso-line-height-rule:exactly=\n;"><![endif]--><div style=3D"Margin:0px auto;max-width:600px;"><table align=\n=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presen=\ntation" style=3D"width:100%;"><tbody><tr><td style=3D"direction:ltr;font-si=\nze:0px;padding:20px 0;padding-bottom:0;text-align:center;vertical-align:top=\n;"><!--[if mso | IE]><table role=3D"presentation" border=3D"0" cellpadding=\n=3D"0" cellspacing=3D"0"><tr><td class=3D"" style=3D"vertical-align:top;wid=\nth:600px;" ><![endif]--><div class=3D"mj-column-per-100 outlook-group-fix" =\nstyle=3D"font-size:13px;text-align:left;direction:ltr;display:inline-block;=\nvertical-align:top;width:100%;"><table border=3D"0" cellpadding=3D"0" cells=\npacing=3D"0" role=3D"presentation" style=3D"vertical-align:top;" width=3D"1=\n00%"><tr><td align=3D"center" style=3D"font-size:0px;padding:10px 25px;word=\n-break:break-word;"><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0"=\n role=3D"presentation" style=3D"border-collapse:collapse;border-spacing:0px=\n;"><tbody><tr><td style=3D"width:255px;"><img alt=3D"" height=3D"auto" src=\n=3D"https://www.equinem.com/static/img/pareg/icon_1024x1024.png" style=3D"b=\norder:0;display:block;outline:none;text-decoration:none;height:auto;width:1=\n00%;" width=3D"255"></td></tr></tbody></table></td></tr><tr><td align=3D"le=\nft" style=3D"font-size:0px;padding:10px 25px;word-break:break-word;"><div s=\ntyle=3D"font-family:\'Helvetica Neue\', Helvetica, Arial, sans-serif;font-siz=\ne:16px;font-weight:400;line-height:24px;text-align:left;color:#000000;"></d=\niv></td></tr><tr><td align=3D"left" style=3D"font-size:0px;padding:10px 25p=\nx;word-break:break-word;"><div style=3D"font-family:\'Helvetica Neue\', Helve=\ntica, Arial, sans-serif;font-size:16px;font-weight:400;line-height:24px;tex=\nt-align:left;color:#000000;"></div></td></tr></table></div><!--[if mso | IE=\n]></td></tr></table><![endif]--></td></tr></tbody></table></div><!--[if mso=\n | IE]></td></tr></table><![endif]--></td></tr></tbody></table><!--[if mso =\n| IE]><table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D=\n"0" class=3D"" style=3D"width:600px;" width=3D"600" ><tr><td style=3D"line-=\nheight:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]--><div st=\nyle=3D"background:#22243f;background-color:#22243f;Margin:0px auto;max-widt=\nh:600px;"><table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacin=\ng=3D"0" role=3D"presentation" style=3D"background:#22243f;background-color:=\n#22243f;width:100%;"><tbody><tr><td style=3D"direction:ltr;font-size:0px;pa=\ndding:20px 0;text-align:center;vertical-align:top;"><!--[if mso | IE]><tabl=\ne role=3D"presentation" border=3D"0" cellpadding=3D"0" cellspacing=3D"0"><t=\nr><td class=3D"" style=3D"vertical-align:top;width:600px;" ><![endif]--><di=\nv class=3D"mj-column-per-100 outlook-group-fix" style=3D"font-size:13px;tex=\nt-align:left;direction:ltr;display:inline-block;vertical-align:top;width:10=\n0%;"><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presen=\ntation" style=3D"vertical-align:top;" width=3D"100%"></table></div><!--[if =\nmso | IE]></td></tr></table><![endif]--></td></tr></tbody></table></div><!-=\n-[if mso | IE]></td></tr></table><table align=3D"center" border=3D"0" cellp=\nadding=3D"0" cellspacing=3D"0" class=3D"body-section-outlook" style=3D"widt=\nh:600px;" width=3D"600" ><tr><td style=3D"line-height:0px;font-size:0px;mso=\n-line-height-rule:exactly;"><![endif]--><div class=3D"body-section" style=\n=3D"-webkit-box-shadow: 1px 4px 11px 0px rgba(0, 0, 0, 0.15); -moz-box-shad=\now: 1px 4px 11px 0px rgba(0, 0, 0, 0.15); box-shadow: 1px 4px 11px 0px rgba=\n(0, 0, 0, 0.15); Margin: 0px auto; max-width: 600px;"><table align=3D"cente=\nr" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presentation" s=\ntyle=3D"width:100%;"><tbody><tr><td style=3D"direction:ltr;font-size:0px;pa=\ndding:20px 0;padding-bottom:0;padding-top:0;text-align:center;vertical-alig=\nn:top;"><!--[if mso | IE]><table role=3D"presentation" border=3D"0" cellpad=\nding=3D"0" cellspacing=3D"0"><tr><td class=3D"" width=3D"600px" ><table ali=\ngn=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" class=3D"" s=\ntyle=3D"width:600px;" width=3D"600" ><tr><td style=3D"line-height:0px;font-=\nsize:0px;mso-line-height-rule:exactly;"><![endif]--><div style=3D"backgroun=\nd:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;"><table=\n align=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"=\npresentation" style=3D"background:#ffffff;background-color:#ffffff;width:10=\n0%;"><tbody><tr><td style=3D"direction:ltr;font-size:0px;padding:20px 0;pad=\nding-left:15px;padding-right:15px;text-align:center;vertical-align:top;"><!=\n--[if mso | IE]><table role=3D"presentation" border=3D"0" cellpadding=3D"0"=\n cellspacing=3D"0"><tr><td class=3D"" style=3D"vertical-align:top;width:570=\npx;" ><![endif]--><div class=3D"mj-column-per-100 outlook-group-fix" style=\n=3D"font-size:13px;text-align:left;direction:ltr;display:inline-block;verti=\ncal-align:top;width:100%;"><table border=3D"0" cellpadding=3D"0" cellspacin=\ng=3D"0" role=3D"presentation" style=3D"vertical-align:top;" width=3D"100%">=\n<tr><td align=3D"left" style=3D"font-size:0px;padding:10px 25px;word-break:=\nbreak-word;"><div style=3D"font-family:\'Helvetica Neue\', Helvetica, Arial, =\nsans-serif;font-size:16px;font-weight:400;line-height:24px;text-align:left;=\ncolor:#22243f;"><h1>Welkom bij PaReg</h1></div></td></tr><tr><td align=3D"l=\neft" style=3D"font-size:0px;padding:10px 25px;word-break:break-word;"><div =\nstyle=3D"font-family:\'Helvetica Neue\', Helvetica, Arial, sans-serif;font-si=\nze:16px;font-weight:400;line-height:24px;text-align:left;color:#637381;">Ha=\nllo {{user}},</div></td></tr><tr><td align=3D"left" style=3D"font-size:0px;=\npadding:10px 25px;word-break:break-word;"><div style=3D"font-family:\'Helvet=\nica Neue\', Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;line=\n-height:24px;text-align:left;color:#637381;">Bevestig uw account door op on=\nderstaande knop te drukken.</div></td></tr><tr><td align=3D"center" vertica=\nl-align=3D"middle" style=3D"font-size:0px;padding:10px 25px;padding-bottom:=\n0;word-break:break-word;"><table border=3D"0" cellpadding=3D"0" cellspacing=\n=3D"0" role=3D"presentation" style=3D"border-collapse:separate;line-height:=\n100%;"><tr><td align=3D"center" bgcolor=3D"#22243f" role=3D"presentation" s=\ntyle=3D"border:none;border-radius:3px;cursor:auto;padding:10px 25px;backgro=\nund:#22243f;" valign=3D"middle"><a href=3D"{{ activate_url }}" style=3D"bac=\nkground:#22243f;color:#ffffff;font-family:\'Helvetica Neue\', Helvetica, Aria=\nl, sans-serif;font-size:13px;font-weight:normal;line-height:120%;Margin:0;t=\next-decoration:none;text-transform:none;" target=3D"_blank">Verifieer email=\nadres</a></td></tr></table></td></tr><tr><td align=3D"center" style=3D"font=\n-size:0px;padding:10px 25px;padding-top:0;padding-bottom:0;word-break:break=\n-word;"><div style=3D"font-family:\'Helvetica Neue\', Helvetica, Arial, sans-=\nserif;font-size:12px;font-weight:400;line-height:24px;text-align:center;col=\nor:#000000;">{{activate_url}}<br>Kopieer dit in een browser als de knop nie=\nt werkt.</div></td></tr></table></div><!--[if mso | IE]></td><td class=3D""=\n style=3D"vertical-align:top;width:570px;" ><![endif]--><div class=3D"mj-co=\nlumn-per-100 outlook-group-fix" style=3D"font-size:13px;text-align:left;dir=\nection:ltr;display:inline-block;vertical-align:top;width:100%;"><table bord=\ner=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presentation" style=3D=\n"vertical-align:top;" width=3D"100%"><tr><td align=3D"left" style=3D"font-s=\nize:0px;padding:10px 25px;padding-top:40px;padding-bottom:0px;word-break:br=\neak-word;"><div style=3D"font-family:\'Helvetica Neue\', Helvetica, Arial, sa=\nns-serif;font-size:16px;font-weight:400;line-height:24px;text-align:left;co=\nlor:#637381;">Wij wensen u namens alle sponsoren en het hele team van PaReg=\n veel gemak bij het registreren van de locatie van de paarden!</div></td></=\ntr></table></div><!--[if mso | IE]></td><td class=3D"" style=3D"vertical-al=\nign:top;width:570px;" ><![endif]--><div class=3D"mj-column-per-100 outlook-=\ngroup-fix" style=3D"font-size:13px;text-align:left;direction:ltr;display:in=\nline-block;vertical-align:top;width:100%;"><table border=3D"0" cellpadding=\n=3D"0" cellspacing=3D"0" role=3D"presentation" style=3D"vertical-align:top;=\n" width=3D"100%"><tr><td align=3D"left" style=3D"font-size:0px;padding:10px=\n 25px;padding-top:40px;padding-bottom:0px;word-break:break-word;"><div styl=\ne=3D"font-family:\'Helvetica Neue\', Helvetica, Arial, sans-serif;font-size:1=\n6px;font-weight:400;line-height:24px;text-align:left;color:#637381;">Voor v=\nragen kunt u ons via email bereiken: <a href=3D"mailto:info@pareg.nl">info@=\npareg.nl</a></div></td></tr></table></div><!--[if mso | IE]></td></tr></tab=\nle><![endif]--></td></tr></tbody></table></div><!--[if mso | IE]></td></tr>=\n</table></td></tr></table><![endif]--></td></tr></tbody></table></div><!--[=\nif mso | IE]></td></tr></table><![endif]--><table align=3D"center" border=\n=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presentation" style=3D"w=\nidth:100%;"><tbody><tr><td><!--[if mso | IE]><table align=3D"center" border=\n=3D"0" cellpadding=3D"0" cellspacing=3D"0" class=3D"" style=3D"width:600px;=\n" width=3D"600" ><tr><td style=3D"line-height:0px;font-size:0px;mso-line-he=\night-rule:exactly;"><![endif]--><div style=3D"Margin:0px auto;max-width:600=\npx;"><table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D"=\n0" role=3D"presentation" style=3D"width:100%;"><tbody><tr><td style=3D"dire=\nction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top=\n;"><!--[if mso | IE]><table role=3D"presentation" border=3D"0" cellpadding=\n=3D"0" cellspacing=3D"0"><tr><td class=3D"" width=3D"600px" ><table align=\n=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" class=3D"" sty=\nle=3D"width:600px;" width=3D"600" ><tr><td style=3D"line-height:0px;font-si=\nze:0px;mso-line-height-rule:exactly;"><![endif]--><div style=3D"Margin:0px =\nauto;max-width:600px;"><table align=3D"center" border=3D"0" cellpadding=3D"=\n0" cellspacing=3D"0" role=3D"presentation" style=3D"width:100%;"><tbody><tr=\n><td style=3D"direction:ltr;font-size:0px;padding:20px 0;text-align:center;=\nvertical-align:top;"><!--[if mso | IE]><table role=3D"presentation" border=\n=3D"0" cellpadding=3D"0" cellspacing=3D"0"><tr><td class=3D"" style=3D"vert=\nical-align:top;width:600px;" ><![endif]--><div class=3D"mj-column-per-100 o=\nutlook-group-fix" style=3D"font-size:13px;text-align:left;direction:ltr;dis=\nplay:inline-block;vertical-align:top;width:100%;"><table border=3D"0" cellp=\nadding=3D"0" cellspacing=3D"0" role=3D"presentation" width=3D"100%"><tbody>=\n<tr><td style=3D"vertical-align:top;padding:0;"><table border=3D"0" cellpad=\nding=3D"0" cellspacing=3D"0" role=3D"presentation" width=3D"100%"><!-- <mj-=\nsocial font-size=3D"15px" icon-size=3D"30px" mode=3D"horizontal" padding=3D=\n"0" align=3D"center">\n            <mj-social-element name=3D"facebook" href=3D"https://www.facebo=\nok.com/EquineM1/" background-color=3D"#A1A0A0">\n            </mj-social-element>\n          </mj-social> --><!-- <mj-text color=3D"#445566" font-size=3D"11px=\n" font-weight=3D"bold" align=3D"center">\n            View this email in your browser\n          </mj-text> --><tr><td align=3D"center" style=3D"font-size:0px;pad=\nding:10px 25px;word-break:break-word;"><div style=3D"font-family:\'Helvetica=\n Neue\', Helvetica, Arial, sans-serif;font-size:11px;font-weight:400;line-he=\night:16px;text-align:center;color:#445566;">{% blocktrans trimmed %} You ar=\ne receiving this email because you signed up for PaReg. {% endblocktrans %}=\n</div></td></tr><tr><td align=3D"center" style=3D"font-size:0px;padding:10p=\nx 25px;word-break:break-word;"><div style=3D"font-family:\'Helvetica Neue\', =\nHelvetica, Arial, sans-serif;font-size:11px;font-weight:400;line-height:16p=\nx;text-align:center;color:#445566;">&copy; EquineM B.V., {% trans \'All Righ=\nts Reserved.\' %}</div></td></tr></table></td></tr></tbody></table></div><!-=\n-[if mso | IE]></td></tr></table><![endif]--></td></tr></tbody></table></di=\nv><!--[if mso | IE]></td></tr></table></td></tr><tr><td class=3D"" width=3D=\n"600px" ><table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=\n=3D"0" class=3D"" style=3D"width:600px;" width=3D"600" ><tr><td style=3D"li=\nne-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]--><div=\n style=3D"Margin:0px auto;max-width:600px;"><table align=3D"center" border=\n=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presentation" style=3D"w=\nidth:100%;"><tbody><tr><td style=3D"direction:ltr;font-size:0px;padding:20p=\nx 0;padding-top:0;text-align:center;vertical-align:top;"><!--[if mso | IE]>=\n<table role=3D"presentation" border=3D"0" cellpadding=3D"0" cellspacing=3D"=\n0"><tr><td class=3D"" style=3D"width:600px;" ><![endif]--><div class=3D"mj-=\ncolumn-per-100 outlook-group-fix" style=3D"font-size:0;line-height:0;text-a=\nlign:left;display:inline-block;width:100%;direction:ltr;"><!--[if mso | IE]=\n><table role=3D"presentation" border=3D"0" cellpadding=3D"0" cellspacing=3D=\n"0"><tr><td style=3D"vertical-align:top;width:600px;" ><![endif]--><div cla=\nss=3D"mj-column-per-100 outlook-group-fix" style=3D"font-size:13px;text-ali=\ngn:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">=\n<table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presentatio=\nn" width=3D"100%"><tbody><tr><td style=3D"vertical-align:top;padding-right:=\n0;"><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"present=\nation" width=3D"100%"><tr><td align=3D"center" style=3D"font-size:0px;paddi=\nng:10px 25px;word-break:break-word;"><div style=3D"font-family:\'Helvetica N=\neue\', Helvetica, Arial, sans-serif;font-size:11px;font-weight:bold;line-hei=\nght:16px;text-align:center;color:#445566;"><a class=3D"footer-link" href=3D=\n"{% url \'site1:privacy\' %}" style=3D"color: #888888;">{% trans \'Privacy\' %}=\n</a></div></td></tr></table></td></tr></tbody></table></div><!--[if mso | I=\nE]></td></tr></table><![endif]--></div><!--[if mso | IE]></td></tr></table>=\n<![endif]--></td></tr></tbody></table></div><!--[if mso | IE]></td></tr></t=\nable></td></tr></table><![endif]--></td></tr></tbody></table></div><!--[if =\nmso | IE]></td></tr></table><![endif]--></td></tr></tbody></table></div></b=\nody></html>\n--===============5112651050379218236==--\n'`

When we send this email post_office does not store that it is encoded as quoted printable. And sends it as 7bit, see line https://github.com/ui/django-post_office/blob/a20c3e705da6705452ad501d6c70615b35344965/post_office/models.py#L133-L139
Thus rendering the email unreadable for the user.

I'm not sure how to fix this. There are 2 options:
1. First decode the html message when storing in the database (in the backend)
2. Store that the html message is stored as quoted_printable and set the correct headers in prepare_email_message

**Comment by gabn88** [comment]
For fix option 1 we can use 
```
import quopri (standard python library)
if part['Content-Transfer-Encoding'] == 'quoted-printable':
    html_body = quopri.decodestring(html_body)
```

**Comment by gabn88** [comment]
Or we could always decode the html_message from the database in line https://github.com/ui/django-post_office/blob/a20c3e705da6705452ad501d6c70615b35344965/post_office/models.py#L119

For example by adding:
`html_message = quopri.decodestring(html_message)`

Advantage of this approach is that everything already in the database also gets send correctly. Disadvantage is that sometimes decoding is not necessary and it will be decoded anyway.

**Comment by gabn88** [comment]
@selwin Please answer which way is your preferred way of solving this, then I'll submit a PR.

**Comment by selwin** [comment]
Hey I'm not familiar with this so please excuse my potentially silly questions.
1. Can we reliably detect if a message needs to be decoded during delivery?
2. Does option 2 require us adding a field in the DB that flags the email as `quoted_printable`?

**Comment by gabn88** [comment]
Hi I'm not a decoding expert. But I've found out in production that option 1 is the safest bet. There is even a `decode=True` argument on the `part.get_payload(decode=True)` function that can be used. I have therefore updated the pull request to reflect this. With this patch emails are being stored correctly in the database.

Option 2 is more difficult (decoding the html after you get it out of the database), although I had some success with the decodestring method in combination with .decode('latin1'). Utf-8 does not work to decode this string from bytestring which is a bit weird. The decodestring will also sometimes raise a ValueError, so it needs to be within a try except block. I have done that here: https://github.com/gabn88/django-post_office/tree/gabn88-tmp-patch and I'm now using this fork in production. With this patch emails are being send correctly even if they are not stored correctly in the database.

1. I think not because the information is lost when it is stored in the database. Therefore I recommend option 1, which decodes the html from get_payload before storing in the database. Another option I found out is to use email_message.body for the plain/text and email_message.alternatives[0] for the html. This is not encoded and thus also doesn't need decoding.

2. Maybe, it is also possible to use a try ... except block and try to decode everything. But I'm not sure if it won't break anything, therefore we would need some real life cases and see what the decoding does exactly.

**Comment by gabn88** [comment]
@selwin I have updated the pull request. Also I found out that for very long emails I have the same problem with the plain/text email. So I have also updated this code. I use a django function for storing the correct plain/text and html now, as far as I can tell it is actually better than the current approach of using a for loop.

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-post_office/pull/420
