### ISSUE TITLE
Already rendered Email is re-rendered without context

### ISSUE THREAD

**Issue by productaize** [ui/django-post_office#421]
In closing #403 a change was made to save the template independent of the render_on_delivery flag. This now causes the email to be re-rendered, however without the context. The result is the empty template message (placeholders are replaced with blank).

Either this should be changed to only re-render if Email.message or Email.html_message is empty, or the context should always be stored, as hinted here [on 24 Aug](https://github.com/ui/django-post_office/pull/403#issuecomment-1226085062)

[django-post_office/post_office/models.py](https://github.com/ui/django-post_office/blob/dddde78411a28f8a5264cfd5244661c6cb75ab88/post_office/models.py#L108)

**Comment by zagl** [comment]
If the context is also just stored and nothing else changed it would be `render_on_delivery=True` by default.

If the context also "can be usefull for admin purposes" it should be saved and Email.message and Email.html_message should be checked for beeing empty.

If the context should not be saved the line
https://github.com/ui/django-post_office/blob/dddde78411a28f8a5264cfd5244661c6cb75ab88/post_office/models.py#L108
could simply be replaced by
`if self.context is not None:`

I created a pull request for the latter.

**Comment by gabn88** [comment]
This commit creates a problem with emails that have a context, but no template. I get "AttributeError: 'NoneType' object has no attribute 'subject'". 

`subject = engine.from_string(self.template.subject).render(self.context)`
