### ISSUE TITLE
Add reply_to attribute to mail.send()

### ISSUE THREAD

**Issue by sebastian-muthwill** [ui/django-post_office#431]
Currently it is not possible to add a reply to address to mail.send(). 
Instead it is necessary to use EmailMultiAlternatives. However this way is not so convenient and self explanatory. 

I would suggest to add the attribute reply_to to the mail.send() function.

**Comment by selwin** [comment]
Mind opening a PR for this?

**Comment by sebastian-muthwill** [comment]
Here we are 2 years later and the `reply_to` started bothering me again. 

Good news, there is no implementation needed and it is working out of the box.

I try to explain it so it may help others as well.

I use post_office for sending all my emails but have some functions that use the django internal mail objects when I had to include a 'reply_to' address. I started to wonder once I realised that those mails are also handled by the post_office queue. 
So I inspected this element since the information `reply_to` had to be stored there somehow. 

```
{'id': 465, 
'from_email': 'Example<hello@example.com>', 
'to': ['to@me.de'], 'cc': [], 'bcc': [], 
'subject': 'Subject', 'message': "Test', '
status': 0, 'priority': 0, '
created': datetime.datetime(2024, 11, 23, 13, 45, 6, 477492, tzinfo=datetime.timezone.utc), 
'last_updated': datetime.datetime(2024, 11, 23, 13, 45, 6, 477508, tzinfo=datetime.timezone.utc), 
'scheduled_time': None, 
'expires_at': None, 
'message_id': '<12345@example.com>',
 'number_of_retries': None,
 'headers': {'Reply-To': 'replytome@me.de'},  # <-- is added 
 'template_id': None, 
'context': None,
 'backend_alias': ''}
``` 

And indeed it is stored as a `header` information. Knowing this, it is now easy to add the same to the post_office `mail` object 🥳
Works like a charm. 

```
from post_office import mail

mail.send(subject="Subject",
                  sender=from_email,
                  message=txt_msg,
                  recipients=resipients_list,
                  priority=priority,
                  headers={'Reply-To': 'replytome@me.de'})
```

Hope that helps.
