### ISSUE TITLE
When using celery emails are not sent directly

### ISSUE THREAD

**Issue by mrudelle** [ui/django-post_office#435]
After following the recommendations under "Integration with celery" on [this page](https://pypi.org/project/django-post-office/). I cannot get the emails to be sent directly via a celery worker. They only get sent on the periodic `post_office.tasks.send_queued_mail` task.

The only way to get them sent directly is when using `"DEFAULT_PRIORITY": "now"` but that uses the request threads, not celery.

`celery.py` looks like this:
```python
from celery import Celery
from celery.schedules import crontab

app = Celery('gallery')
app.config_from_object('django.conf:settings', namespace='CELERY')

app.autodiscover_tasks()

app.conf.beat_schedule = {
...
}
```

and settings.py:
```python
...
EMAIL_BACKEND = 'post_office.EmailBackend'
POST_OFFICE = {
    'CELERY_ENABLED': True,
    'DEFAULT_PRIORITY': 'high',
    'CONTEXT_FIELD_CLASS': 'picklefield.fields.PickledObjectField',
    'BACKENDS': {
        'default': 'django_ses.SESBackend'
    },
}
...
```

And the celery workers outputs this:
```
 -------------- celery@df2501fcf935 v5.2.7 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-***
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         ***
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . ... some other tasks ...
  . post_office.tasks.cleanup_mail
  . post_office.tasks.send_queued_mail

```

`app.autodiscover_tasks()` is called, as mentioned in the doc. But emails are still sent during the periodic `post_office.tasks.send_queued_mail`, not directly. 

Am I missing a configuration somewhere?

**Comment by gabn88** [comment]
I have the same problem. Thought it was a configuration issue on my side. I now use 1 minute interval for checking, but 1 minute is still a lot when waiting for a confirmation email.

**Comment by wlcx** [comment]
I ran into this - it seems the concept of `priority="now"` is a bit misleading when using this with celery.

`priority="now"` directly sends the message and bypasses celery entirely, as you observed. See https://github.com/ui/django-post_office/blob/master/post_office/mail.py#L162.

If celery is enabled and you don't use `priority="now"`, emails are still sent immediately - a call to `mail.send` triggers the `send_queued_mail` celery task, which immediately sends the email you wanted, as well as any other queued ones. Priority (other than "now") then simply determines the order the mail is sent in, so it's still worth prioritising time-sensitive emails as "high".

I think the docs could do with being updated to explain this a bit better!

**Comment by diesieben07** [comment]
Actually the `email_queued` signal is not sent if you just use Django's `send_mail` or otherwise go through Django's API. The email will then end up in Post Office's [`EmailBackend#send_messages`](https://github.com/ui/django-post_office/blob/9acc56f2c38f36862c296fea587879dc776f80a8/post_office/backends.py#L16). This calls [`create`](https://github.com/ui/django-post_office/blob/9acc56f2c38f36862c296fea587879dc776f80a8/post_office/mail.py#L42) to create the email, but the `email_queued` signal is not sent if the priority is not `NOW`. The `email_queued` signal is only sent if you use the (Post Office specific) functions [`send`](https://github.com/ui/django-post_office/blob/9acc56f2c38f36862c296fea587879dc776f80a8/post_office/mail.py#L133) or [`send_many`](https://github.com/ui/django-post_office/blob/9acc56f2c38f36862c296fea587879dc776f80a8/post_office/mail.py#L239).
A call to `email_queued.send(...)` should be added [here](https://github.com/ui/django-post_office/blob/9acc56f2c38f36862c296fea587879dc776f80a8/post_office/backends.py#L69), based on the default prority.

**Comment by diesieben07** [comment]
I looked into this more, here is what I found:

- `utils.send_mail`: This claims to be a replacement for Django's `send_mail` function (it behaves differently though in various ways). This does **not** start the queue task.
- `mail.send`: Sends `email_queued` regardless of priority. It should not be sent for priority "now" (but this does not have any serious ill effects).
- `mail.send_many`: Claims it cannot handle priority="now", but just calls `send` repeatedly for all mails (which will send them one after the other in case of priority "now"). This also causes `email_queued` to be sent N+1 times for N emails (N times by `send` and once by `send_many`).
- `EmailBackend.send_messages`: Like said above, does not send `email_queued`

These are all I could find and I will try to prepare a pull request to fix these.

**Comment by gabn88** [comment]
@diesieben07 Good observation. Did you manage to create a PR to fix this longstanding issue?

**Comment by diesieben07** [comment]
@gabn88 I must admit, I completely forgot about doing that, thank you for reminding me. I can't promise that I'll get to it this week, but I do still want to fix it.

**Comment by hng** [comment]
I have the same issue. I would be willing to help put forward an PR and test it @diesieben07

**Comment by diesieben07** [comment]
Hi @hng, if you want, please check out my PR #469!

**Comment by gabn88** [comment]
This is great news, I missed it because of other priorities, but got bitten again by it today. Thanks @diesieben07!
