### ISSUE TITLE
Recipients emails should support display name

### ISSUE THREAD

**Issue by LeGast00n** [ui/django-post_office#73]
Hi there,

I'm getting a ValidationError when sending mails with display names, e.g. John Smith <john.smith@acme.gov>

Want to fix it?

Put the following lines in utils:

    import re
    from django.core.validators import EmailValidator
    
    class FullEmailValidator(EmailValidator):
        """ Simple validator that passes for email addresses bearing a display name
        i.e. John Smith <john.smith@acme.gov>
        """
        def __call__(self, value):
            try:
                res = super(FullEmailValidator, self).__call__(value)
            except ValidationError:
                try:
                    split_address = re.match(r'(.+) \<(.+@.+)\>', value)
                    display_name, email = split_address.groups()
                    super(FullEmailValidator, self).__call__(email)
                except AttributeError:
                    raise ValidationError

    validate_email = FullEmailValidator()

Also, in utils replace in validate_comma_separated_emails() the call to validate_email by **validate_email_with_name**:

    def validate_comma_separated_emails(value):
    """
    Validate every email address in a comma separated list of emails.
    """
        if not isinstance(value, (tuple, list)):
            raise ValidationError('Email list must be a list/tuple.')
    
        for email in value:
            try:
                validate_email_with_name(email)
            except ValidationError:
                raise ValidationError('Invalid email: %s' % email, code='invalid')

cheers

**Comment by gorillamania** [comment]
I'd like to see this finished / merged / released

**Comment by selwin** [comment]
This has been fixed

**Comment by yprez** [comment]
This still doesn't work for me for some reason...

**Comment by yprez** [comment]
Because send() calls `validators.parse_emails()` which calls `django.core.validators.validate_email` directly...
