### ISSUE TITLE
Migrations broken on 1.1.1 (installed via pip/PyPi)

### ISSUE THREAD

**Issue by photojosh** [ui/django-post_office#96]
The migrations directory (not south_migrations) has `0001_initial.py`; which is the correct (and only) migrations file. But then it has `0002_xxx.py` – `0011_xxx.py`, which are South migrations and shouldn't be there.

This results in `./manage.py migrate` not finding any migrations at all. 

(This drove me a little crazy upgrading a legacy system from 0.8.3.)

AFAICT the solution is to repackage 1.1.1 without the culprit migration files.

**Comment by selwin** [comment]
Hi there, I downloaded the source code from PyPI but the migrations folder only has `0001_initial.py`. Perhaps the other files were left over from your previous installation?

Here's the download link: https://pypi.python.org/pypi/django-post_office
