### ISSUE TITLE
Template Inheritance Support

### ISSUE THREAD

**Issue by akanieski** [ui/django-post_office#98]
Does post_office support template inheritance? 

If not I think this would be a great feature. The basic structure of all the branded emails going out of my app is the same. Everytime I make a change I currently make it to all my templates (#fail).

**Comment by selwin** [comment]
I'm not sure whether this is easily achievable. I'm not keen on adding complex templating features to this library. If you have a need for custom templating system, you should render the content of your email using your own system and pass in the full, rendered content to django-post-office.
